// Mock Data for Dashboard

export const STAT_CARDS = [
  {
    id: 1,
    title: "Total Pengguna",
    value: "40,689",
    percentage: "8.5%",
    trend: "up",
    timeframe: "Up from yesterday",
    icon: "Users",
    bgColor: "bg-purple-100",
    iconColor: "text-purple-600",
  },
  {
    id: 2,
    title: "Total Laporan",
    value: "10293",
    percentage: "1.3%",
    trend: "up",
    timeframe: "Up from past week",
    icon: "Package",
    bgColor: "bg-yellow-100",
    iconColor: "text-yellow-600",
  },
  {
    id: 3,
    title: "Total Teratasi",
    value: "1000",
    percentage: "4.3%",
    trend: "down",
    timeframe: "Down from yesterday",
    icon: "TrendingUp",
    bgColor: "bg-green-100",
    iconColor: "text-green-600",
  },
  {
    id: 4,
    title: "Total Pending",
    value: "2040",
    percentage: "1.8%",
    trend: "up",
    timeframe: "Up from yesterday",
    icon: "Clock",
    bgColor: "bg-orange-100",
    iconColor: "text-orange-600",
  },
];

export const CHART_DATA = [
  { name: "5k", value: 40 },
  { name: "10k", value: 30 },
  { name: "15k", value: 35 },
  { name: "20k", value: 50 },
  { name: "25k", value: 49 },
  { name: "30k", value: 60 },
  { name: "35k", value: 70 },
  { name: "40k", value: 75 },
  { name: "45k", value: 80 },
  { name: "50k", value: 85 },
  { name: "55k", value: 90 },
  { name: "60k", value: 88 },
];

export const TABLE_DATA = [
  {
    id: 1,
    productName: "Apple Watch",
    productInitials: "AW",
    productBgColor: "bg-red-500",
    location: "6096 Marjolaine Landing",
    dateTime: "12.09.2019 - 12:53 PM",
    piece: 423,
    amount: "$34,295",
    status: "Delivered",
  },
  {
    id: 2,
    productName: "iPhone 14 Pro",
    productInitials: "IP",
    productBgColor: "bg-blue-500",
    location: "4812 August Street",
    dateTime: "12.09.2019 - 01:20 PM",
    piece: 210,
    amount: "$28,450",
    status: "Pending",
  },
  {
    id: 3,
    productName: "iPad Air",
    productInitials: "IA",
    productBgColor: "bg-amber-400",
    location: "2345 Blake Street",
    dateTime: "12.09.2019 - 02:45 PM",
    piece: 156,
    amount: "$18,920",
    status: "Processing",
  },
  {
    id: 4,
    productName: "AirPods Pro",
    productInitials: "AP",
    productBgColor: "bg-green-500",
    location: "5678 Market Avenue",
    dateTime: "12.09.2019 - 03:15 PM",
    piece: 89,
    amount: "$12,540",
    status: "Delivered",
  },
  {
    id: 5,
    productName: "MacBook Pro",
    productInitials: "MB",
    productBgColor: "bg-purple-500",
    location: "9012 Oak Boulevard",
    dateTime: "12.09.2019 - 04:30 PM",
    piece: 45,
    amount: "$125,600",
    status: "Cancelled",
  },
];

export const SIDEBAR_MENU = [
  {
    section: "Main",
    items: [
      { label: "Beranda", icon: "Home", href: "/beranda" },
      { label: "Analitik & Prioritas", icon: "TrendingUp", href: "/analitik" },
      { label: "Aduan ", icon: "TrendingUp", href: "/aduan" },
      { label: "Laporan & Rekomendasi", icon: "BarChart3", href: "/laporan" },
    ],
  },
  {
    section: "Pages",
    items: [
      { label: "Inbox", icon: "Mail", href: "/admin/inbox" },
      { label: "Calendar", icon: "Calendar", href: "/admin/calendar" },
      { label: "To-Do", icon: "CheckSquare", href: "/admin/todo" },
      { label: "Team", icon: "Users", href: "/admin/team" },
      { label: "Contact", icon: "Users", href: "/admin/contact" },
      { label: "Invoice", icon: "FileText", href: "/admin/invoice" },
    ],
  },
  {
    section: "Account",
    items: [
      { label: "Settings", icon: "Settings", href: "/admin/settings" },
      { label: "Logout", icon: "LogOut", href: "/logout" },
    ],
  },
];
